title: Кримскотатарската диаспора в България
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Целта ни е да споделяме информация за кримскотатарската диаспора в България. 
  Нашият уебсайт е с отворен код в Github.
  Каним всички да се присъединят към нашата мрежа.
author: krimskitatari @ gmail.com 
# email: krimskitatari@gmail.com
# SPAM olmasın diye 

header_pages:
  - simvoli.md
  - about.md

show_excerpts: false

theme: minima
  minima:
    date_format: "%Y-%m-%d"
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
    skin: dark
    social_links:
    - { platform: github,         user_url: "https://github.com/qirimtatar-net/bg" }
    - { platform: facebook,       user_url: "https://www.facebook.com/qirimtatar.bg" }
    - { platform: twitter,        user_url: "https://twitter.com/krimskitatari" }

  # Generate social links in footer.
  # social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/qirimtatar.bg" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: github,         user_url: "https://github.com/qirimtatar-net/bg" }
  #  - { platform: gitlab,         user_url: "https://gitlab.com/jekyll" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
